'use strict';

var
  weLoveSvgConfig = {
    svgSets: {
      url: '//cdn.rawgit.com/icons8/welovesvg/78f7305/libs',
      libs: [
        'brandico',
        'elusive-icons',
        'entypo',
        'font-awesome',
        'fontelico',
        'foundation-icons',
        'glyphicons-halflings',
        'icomoon-free',
        'icons8-color-icons',
        'icons8-win10',
        'icons8-wpf',
        'ionicons',
        'ligaturesymbols',
        'linecons',
        { lib: 'maki', name: 'maki-12' },
        { lib: 'maki', name: 'maki-18' },
        { lib: 'maki', name: 'maki-24' },
        "material-icons",
        'meteocons',
        'metrize-icons',
        'mfglabs-iconset',
        'octicons',
        'open-iconic',
        'openwebicons',
        'raphael-icons',
        'simple-line-icons',
        'stateface',
        'stroke7',
        'typicons',
        'weather-icons',
        'webhostinghub-glyphs',
        'zocial'
      ]
    },
    aliases: {
      "color-icons": 'icons8-color-icons',
      "flat-color-icons": 'icons8-color-icons',
      "win10": 'icons8-win10',
      "wpf-ui-framework-icons": 'icons8-wpf',
      "wpf": 'icons8-wpf',
      "glyphicons": 'glyphicons-halflings',
      "ion": 'ionicons',
      "lsf": 'ligaturesymbols',
      "maki": 'maki-24',
      "material-design-icons": 'material-icons',
      "material": 'material-icons',
      "weather": 'weather-icons',
      "icomoon": 'icomoon-free',
      "elusive": 'elusive-icons',
      "fa": 'font-awesome',
      "foundation": 'foundation-icons',
      "metrize": 'metrize-icons',
      "mfglabs": 'mfglabs-iconset',
      "iconic": 'open-iconic',
      "raphael": 'raphael-icons',
      "simple-line": 'simple-line-icons',
      "webhostinghub": 'webhostinghub-glyphs'
    }
  };
